apiVersion: batch/v1
kind: Job
metadata:
  name: profx-crawl-job
spec:
  template:
    spec:
      containers:
        - name: profx-crawl-job
          image: index.docker.io/kenanbek/profx:latest
          imagePullPolicy: Always
          command: ["/profx",  "-crawl"]
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
          env:
            - name: DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbc
                  key: username
            - name: DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbc
                  key: password
            - name: DBC_READ_HOST
              value: "private-kn-sfo2-dbc-do-user-7153629-0.db.ondigitalocean.com"
            - name: DBC_READ_PORT
              value: "25060"
            - name: DBC_WRITE_HOST
              value: "private-kn-sfo2-dbc-do-user-7153629-0.db.ondigitalocean.com"
            - name: DBC_WRITE_PORT
              value: "25060"
            - name: DBC_SCHEMA
              value: "profx"
            - name: PROFX_RUN_COUNT
              value: "1"
            #- name: PROFX_RUN_INTERVAL
            #  value: "3600" # every 1 hour
      imagePullSecrets:
        - name: dhregcred
      restartPolicy: Never
  backoffLimit: 2
