apiVersion: v1  
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: flash
spec:
  type: LoadBalancer
  selector:
    app: flash
  ports:
  - name: http
    port: 8080
    targetPort: 8080
